# Google Cloud Build configuration file for backend
# This file defines the steps to build and deploy the backend application

steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/prompt-mixer-backend:$COMMIT_SHA', '.']
    dir: 'backend'
    id: 'build-image'

  # Step 2: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/prompt-mixer-backend:$COMMIT_SHA']
    id: 'push-image'
    waitFor: ['build-image']

  # Step 3: Tag the image as latest
  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'gcr.io/$PROJECT_ID/prompt-mixer-backend:$COMMIT_SHA', 'gcr.io/$PROJECT_ID/prompt-mixer-backend:latest']
    id: 'tag-latest'
    waitFor: ['push-image']

  # Step 4: Push the latest tag
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/prompt-mixer-backend:latest']
    id: 'push-latest'
    waitFor: ['tag-latest']

  # Step 5: Deploy to Cloud Run (uncomment and configure as needed)
  # - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  #   entrypoint: 'gcloud'
  #   args:
  #     - 'run'
  #     - 'deploy'
  #     - 'prompt-mixer-backend'
  #     - '--image=gcr.io/$PROJECT_ID/prompt-mixer-backend:$COMMIT_SHA'
  #     - '--region=us-central1'
  #     - '--platform=managed'
  #     - '--allow-unauthenticated'
  #     - '--port=8000'  # Match the port in run.py
  #     - '--set-env-vars=DATABASE_URL=$$DATABASE_URL,SECRET_KEY=$$SECRET_KEY,GOOGLE_CLIENT_ID=$$GOOGLE_CLIENT_ID,CLAUDE_API_KEY=$$CLAUDE_API_KEY'
  #   id: 'deploy'
  #   waitFor: ['push-image']
  #   secretEnv: ['DATABASE_URL', 'SECRET_KEY', 'GOOGLE_CLIENT_ID', 'CLAUDE_API_KEY']

# Images to be stored in Google Container Registry
images:
  - 'gcr.io/$PROJECT_ID/prompt-mixer-backend:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/prompt-mixer-backend:latest'

# Timeout for the entire build process
timeout: '1200s'

# Optional: Define secrets for environment variables (uncomment and configure as needed)
# availableSecrets:
#   secretManager:
#     - versionName: projects/$PROJECT_ID/secrets/DATABASE_URL/versions/latest
#       env: 'DATABASE_URL'
#     - versionName: projects/$PROJECT_ID/secrets/SECRET_KEY/versions/latest
#       env: 'SECRET_KEY'
#     - versionName: projects/$PROJECT_ID/secrets/GOOGLE_CLIENT_ID/versions/latest
#       env: 'GOOGLE_CLIENT_ID'
#     - versionName: projects/$PROJECT_ID/secrets/CLAUDE_API_KEY/versions/latest
#       env: 'CLAUDE_API_KEY'

# Optional: Define substitutions for variables
# substitutions:
#   _REGION: 'us-central1'
#   _SERVICE_NAME: 'prompt-mixer-backend'
